# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'listen', '~> 3.0'
#gem 'redcarpet'
gem 'kramdown'